version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
environment:
  nodejs_version: 10,
  VUE_APP_BASE_API: https://tarrasque.azurewebsites.net/
install:
- ps: Install-Product node $env:nodejs_version
- npm install
build_script:
- npm run build
artifacts:
- path: dist\
  name: web-app
deploy:
- provider: WebDeploy
  server: https://hgv-desolator.scm.azurewebsites.net:443/msdeploy.axd?site=hgv-desolator
  website: hgv-desolator
  username: $hgv-desolator
  password:
    secure: CXRZfjhTbeN85vMdmNznZ+G+YGhQSk3xgD5NSIVAPYBDnobV8NKMQ4O8CrbBnNuAoJBUVBOWDWtzNygId/9cbA==
  artifact: web-app
  remove_files: true
  app_offline: true