# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm build
      - uses: feeloor/azure-static-website-deploy@master
        env:
          SOURCE_DIR: "./dist"
          AZURE_CLIENT_ID: "<azure-client-id>"
          AZURE_TENANT_ID: "<azure-tenant-id>"
          AZURE_SECRET: "<azure-secret>"
          AZURE_SUBSCRIPTION_ID: "<azure-subscription-id>"
          AZURE_STORAGE_ACCOUNT_NAME: "<azure-storage-account-name>"
          AZURE_INDEX_DOCUMENT_NAME: "<index-document-name>"
          AZURE_ERROR_DOCUMENT_NAME: "<error-document-name>"
